# Generated by Django 4.1 on 2022-08-10 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lojista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('senha', models.CharField(max_length=30)),
                ('ativo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioComum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('senha', models.CharField(max_length=30)),
                ('ativo', models.BooleanField()),
            ],
        ),
    ]
