# Generated by Django 4.1 on 2022-08-10 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='Posui_CNPJ',
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_conta', models.IntegerField()),
                ('Tipo_Conta', models.CharField(max_length=8)),
                ('saldo', models.DecimalField(decimal_places=10, max_digits=19)),
                ('BitAtivo', models.BooleanField()),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.usuario')),
            ],
        ),
    ]
