# Generated by Django 4.1 on 2022-08-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0003_remove_contabancaria_tipo_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contabancaria',
            name='BitAtivo',
            field=models.BooleanField(),
        ),
    ]
