# Generated by Django 4.1 on 2022-08-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0004_alter_contabancaria_bitativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contabancaria',
            name='saldo',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
