# Generated by Django 4.1 on 2022-08-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0005_alter_contabancaria_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contabancaria',
            name='numero_conta',
            field=models.IntegerField(unique=True),
        ),
    ]
