# Generated by Django 4.1 on 2022-08-10 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0006_alter_contabancaria_numero_conta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contabancaria',
            old_name='numero_conta',
            new_name='numero_conta',
        ),
    ]
